### PR TITLE
Update submitted email template and header in template

### PR DESCRIPTION
**Pull request by BaibhaVatsa**

### CODE REVIEW

**Comment by gfting** [comment]
I think it's a little strange to have `%20` in the link; could you make it so that it's `_`? Really minor, everything else looks great!

**Comment by BaibhaVatsa** [comment]
@gfting updated

**Comment by gfting** [comment]
Hmm, I'm not sure if this was pushed. Could you re-push? Thanks!

**Comment by BaibhaVatsa** [comment]
Lmao sorry

**Comment by gfting** [comment]
Awesome, thanks! One tiny quality of life thing I just realized is that we could make our socials link to them–

**Pull request merged**
