### PR TITLE
Improve line spacing on hacker dashboard

### PR DESCRIPTION
**Pull request by aadibajpai**
span doesn't reply to margin and padding, whereas p automatically adds consistent spacing.

the current spacing is inconsistent with rest of the design* 
image

before: 
image

after:
image

*cute dark mode sold separately

### CODE REVIEW

**Comment by aadibajpai** [comment]
@gfting what do you think? 🙂

**Review by BaibhaVatsa — APPROVED** [review]
LGTM

**Comment by BaibhaVatsa** [comment]
I just remembered this but I think you also need to update the snapshot @aadibajpai

**Review by BaibhaVatsa — APPROVED** [review]
LGTM: Round 2

**Review by gfting — APPROVED** [review]
Looks good. Could you also open a quick PR to the event branch to fix this? Thanks!

**Comment by aadibajpai** [comment]
> Looks good. Could you also open a quick PR to the event branch to fix this? Thanks!

#690

**Comment by leonm1** [comment]
This commit made it into `main` already through the `event/vh2020-fall` branch, so closing this. Thank you for your contribution!

**Pull request closed without merging**
