### PR TITLE
Trim whitespace for required questions

### PR DESCRIPTION
**Pull request by aadibajpai**
Currently, you can submit an application with your first name, last name, phone #, school, major as just a bunch of spaces.

This PR prevents that at least for required fields.

We should still have some validation for non-required fields but I am not sure of the best way to go about that.

fixes 4 of Nisala's bugs.

### CODE REVIEW

**Review by nkalupahana — APPROVED** [review]
nice one

**Comment by siraben** [comment]
noice

**Comment by nkalupahana** [comment]
...what happened to the Happo diffs?

**Comment by aadibajpai** [comment]
> ...what happened to the Happo diffs?

I assume just a render thing

**Pull request merged**
