### PR TITLE
add swag size and make address optional

### PR DESCRIPTION
**Pull request by BaibhaVatsa**

### CODE REVIEW

**Comment by gfting** [comment]
Hmm, I think we should merge in the logic for women's shirt sizes as well if this is being merged in.

**Comment by gfting** [comment]
Other than that, this looks good

**Comment by BaibhaVatsa** [comment]
Thoughts on just adding the women's sizes "crudely" (add values to the array listed manually) for now because marketing starts the campaign

**Comment by BaibhaVatsa** [comment]
Merging this in as the logic for women's shirt sizes is in #684

**Pull request merged**
