### PR TITLE
Fix Discord link in hacker dashboard

### PR DESCRIPTION
**Pull request by BaibhaVatsa**

### CODE REVIEW

**Comment by BaibhaVatsa** [comment]
I couldn't find how to set the `noopener` to `null` using this method.

**Comment by gfting** [comment]
@BaibhaVatsa could you include a screenshot of how it appears on your screen?

**Comment by BaibhaVatsa** [comment]
discord fix

About the `rel=noopener` thing, iirc we set that in the `<a>` tags so that the newly opened tab doesn't take control of the window or something similar. I don't know how to set that up in this case.

**Comment by gfting** [comment]
Hmm, does the underlining not work?

**Comment by gfting** [comment]
Anyways, this looks fine. I think this is a fine solution for now. Thanks!

**Pull request merged**
