### PR TITLE
Add stories for remaining components

### PR DESCRIPTION
**Pull request by leonm1**
This adds storybook stories and screenshot diff verification tests for all (? nearly all?) frontend components.

### CODE REVIEW

**Comment by bencooper222** [comment]
Reminder to remove everything involving Jest snapshots if we do this - bunch of random scripts and config associated with them.

**Comment by bencooper222** [comment]
Also as you add stories, can you delete Jest snapshots? There's a bunch that have both right now and I think that's superfluous?

**Comment by leonm1** [comment]
@aadibajpai @bencooper222 @SamLee514 This is officially ready for review, but it's also very dense and I don't expect you to review everything with a fine-toothed-comb. This is more "matt being matt" and sending massive PRs.

Feel free to take a look through the happo screenshots and tests and feel good about hitting that Approve Changes button.

**Comment by SamLee514** [comment]
@leonm1 Should we be worried about the codeclimate checks? Or do those not matter in this context?

**Comment by bencooper222** [comment]
In general with CodeClimate, you should take them as suggestions. I think they're valuable sometimes - https://github.com/VandyHacks/vaken/blob/main/src/server/resolvers/MutationResolvers/updateApplicationResolver.ts really is horrifying but often they get mad about dumb stuff

**Comment by bencooper222** [comment]
Its biggest complaint with the codebase is the NFC stuff and ... yeah that sounds right

**Comment by bencooper222** [comment]
I'll take a look at the code coverage stuff later, the decrease is suss

**Review by SamLee514 — APPROVED** [review]
Screenshots look good!

**Pull request merged**
