### PR TITLE
fall 2020 customizations 

### PR DESCRIPTION
**Pull request by aadibajpai**
add retro logo + dark sidebar
blue doesn't work well with logo at all so that gradient had to go

I still want to figure out colors a bit but low-key taking time to figure out what gets its color from where

### CODE REVIEW

**Comment by aadibajpai** [comment]
I had planned to do like a dark mode but that's beyond the scope here bc this is mainly to bring retro elements and I don't want to delay this part further.

Looks like this 
image

I also made the VandyHacks VII in the bottom left hyperlink to the website :))

**Comment by aadibajpai** [comment]
@BaibhaVatsa helu

**Review by BaibhaVatsa — APPROVED** [review]

**Comment by gfting** [comment]
Thanks @aadibajpai! If you could change the file naming scheme to use _ rather than spaces, this looks ready to merge in.

**Comment by aadibajpai** [comment]
> Thanks @aadibajpai! If you could change the file naming scheme to use _ rather than spaces, this looks ready to merge in.

done, @gfting

**Pull request merged**
