### PR TITLE
Add spacing between confirm and decline buttons

### PR DESCRIPTION
**Pull request by Ace314159**
# Summary

This adds spacing between the confirm and decline buttons after a hacker has been accepted (N-56)

### CODE REVIEW

**Comment by aadibajpai** [comment]
@Ace314159 the space looks awesome, if you look at the happo diffs tho in some of them the button seems to go beyond the outer pink container tho. Try viewing the diffs in the diff option to see the difference.

**Comment by aadibajpai** [comment]
it appears there's even more diffs now

**Comment by Ace314159** [comment]
The diffs seem to be a font issue. Any idea why this might occur? I didn't do anything with fonts and only modified the HackerDash component.

**Comment by nkalupahana** [comment]
Happo is good now :)

**Review by SamLee514 — APPROVED** [review]
good

**Pull request merged**
