### PR TITLE
Add Happo/Storybook to Code coverage

### PR DESCRIPTION
**Pull request by bencooper222**
# Summary
We lost 3% code coverage in #773 because Happo's testing didn't count as code coverage. This resolves that.

### CODE REVIEW

**Comment by bencooper222** [comment]
Blocked by https://github.com/istanbuljs/istanbuljs/issues/572

**Comment by bencooper222** [comment]
so uh there's a memory leak on this PR and the moment I add code to diagnose it... it disappears. GH gives each job 7gb of memory and the max we hit when just testing was 1.9GB.

**Comment by bencooper222** [comment]
Best guess right now is it's MongoDB Memory server's fault. Guess I'll try this https://github.com/shelfio/jest-mongodb

**Review by leonm1 — APPROVED** [review]

**Comment by bencooper222** [comment]
29 lines of code changed (not counting lockfile) across 18 commits - not counting rebased and ones that disappeared with force pushes

**Pull request merged**
