### PR TITLE
Fully automate dev setup with Gitpod

### PR DESCRIPTION
**Pull request by leonm1**
This commit implements a fully-automated development setup using Gitpod.io, an
online IDE for GitHub and GitLab that enables Dev-Environments-As-Code.
This makes it easy for anyone to get a ready-to-code workspace for any branch,
issue or pull request almost instantly with a single click.

### CODE REVIEW

**Comment by leonm1** [comment]
@bencooper222 would like to hear what you think about gitpod - it seems like a good way to lower the bar for drop-in contributions (even if they're internal)

**Comment by bencooper222** [comment]
It looks cool. Is there a way I can try out the stuff you've done on this PR?

**Comment by leonm1** [comment]
You can test it out from the source branch: https://github.com/VandyHacks/vaken/tree/leonm1/gitpod-setup

There's a badge in the README

**Comment by leonm1** [comment]
This never fully worked properly and might be best closed and reopening pending successful merge of #630

**Pull request closed without merging**
