### PR TITLE
Update all dependencies to latest version, respecting semver

### PR DESCRIPTION
**Pull request by bencooper222**
Boring

### CODE REVIEW

**Comment by cktang88** [comment]
closes #57

**Comment by bencooper222** [comment]
It does? I literally just ran `npm update`. I didn't change anything else.

**Comment by cktang88** [comment]
Oh, nvm then. We still need to upgrade major versions then?

**Comment by bencooper222** [comment]
Oh, yeah that is correct. Sorry, I thought the issue you said this fixed was the unnecessary dependency one. It does fix #57 unless you meant for that issue to also track us being behind on major versions.

**Comment by cktang88** [comment]
Yeah, 57 is meant to update all deps as long as they don't require substantial code changes

**Comment by bencooper222** [comment]
I think I agree with your initial assessment that #57 should be closed after this was merged.

**Comment by cktang88** [comment]
I think upgrading major versions is important though - most of the time they have minor, if any, syntax changes - stuff that can easily be fixed by find/replace, etc.

**Comment by bencooper222** [comment]
Agreed - you should either clarify it in the issue or close that issue and make a new one. I prefer the latter but it doesn't matter.

**Pull request merged**
