### PR TITLE
Add nvm

### PR DESCRIPTION
**Pull request by bencooper222**
I think this is the right call.

- Helps consistency
- Makes setup easier (particularly since dev environments are going to be on two different CPU architectures soon)

### CODE REVIEW

**Review by leonm1 — CHANGES_REQUESTED** [review]
Can you add this to the `scripts/install.sh` file as well?

**Comment by bencooper222** [comment]
I did think about doing that but installing on *nix systems is involved [enough](https://github.com/nvm-sh/nvm#installing-and-updating) (it's not a one command thing) that I don't think we can automate it.

Not to mention people who already have nvm would find the script a hassle then or the few Windows users not on WSL

**Review by leonm1 — APPROVED** [review]

**Review by leonm1 — CHANGES_REQUESTED** [review]
I think this might need changed re the "got added in rebase"

**Comment by bencooper222** [comment]
Oh that's just removing a dep that we removed in #762  that I accidentally added back when rebasing this PR.

**Comment by bencooper222** [comment]
@leonm1 approve pls

**Review by leonm1 — APPROVED** [review]

**Pull request merged**
